"""Deposit-Snapshot — schlanke, deponierfähige Fassung des Korpus (Option B).

Erzeugt aus dem Roh-Cache `refs.jsonl` einen eingefrorenen Snapshot mit nur den
genutzten bibliografischen Feldern plus den ABGELEITETEN Spalten (Stadt, Land,
Region, Senior-Flag). KEIN Analyse-Code, KEINE Disambiguierungs-Logik — die wird
mit dem Methodenpaper [10] veröffentlicht. Lizenz für das Deposit: CC0/CC-BY;
zugrunde liegende Records stammen aus OpenAlex (CC0).

Pro Artikel:
  id, doi, publication_year, title, type, journal{id,name},
  countries (ISO-2), centres (Vereinigung der strikten Radonc-Städte),
  authors[]: { position, author_id, name, cities[], country, region, is_senior }

Schreibt:
  outputs/dataset/corpus_snapshot.jsonl      ein Record pro Artikel
  outputs/dataset/corpus_provenance.json     Kopie des Manifests (Bauanleitung)
  outputs/dataset/README.md                  Kurzbeschreibung + Lizenz + Feldliste

Aufruf:  python export_snapshot.py
"""
from __future__ import annotations

import json
import shutil

import config
import radonc_common as rc
import radonc_geo as g

DATASET = config.OUTPUTS / "dataset"


def author_record(a: dict, senior_ids: set, senior_keys: set) -> dict:
    au = a.get("author") or {}
    cities = sorted(g.author_cities(a))
    country = config.country_of(cities[0]) if cities else None
    region = config.region_of(cities[0]) if cities else None
    return {
        "position": a.get("author_position"),
        "author_id": au.get("id"),
        "name": au.get("display_name"),
        "cities": cities,
        "country": country,
        "region": region,
        "is_senior": g.is_known_senior(a, senior_ids, senior_keys),
    }


def article_record(w: dict, senior_ids: set, senior_keys: set) -> dict:
    pl = w.get("primary_location") or {}
    src = pl.get("source") or {}
    authors = [author_record(a, senior_ids, senior_keys)
               for a in w.get("authorships", [])]
    centres = sorted({c for a in authors for c in a["cities"]})
    return {
        "id": w.get("id"),
        "doi": w.get("doi"),
        "publication_year": w.get("publication_year"),
        "title": w.get("title"),
        "type": w.get("type"),
        "journal": {"id": src.get("id"), "name": src.get("display_name")},
        "countries": sorted(rc.work_countries(w)),
        "centres": centres,
        "authors": authors,
    }


README = """\
# DACH Radiation-Oncology Corpus — Deposit Snapshot

Frozen snapshot of the corpus underlying the study *"The Coming of Age of a Young
Specialty: The Evolution of German-Speaking Radiation Oncology Research, 2000–2025"*.

## Files
- `corpus_snapshot.jsonl` — one JSON record per article (see fields below).
- `corpus_provenance.json` — machine-readable corpus-construction manifest: the exact
  OpenAlex queries, filter parameters, and article counts at each stage, with a
  generation timestamp. The corpus can be reconstructed independently from these
  queries.

## Record fields (`corpus_snapshot.jsonl`)
- `id`, `doi`, `publication_year`, `title`, `type`
- `journal`: `{id, name}` (OpenAlex source)
- `countries`: ISO-2 country codes of the article's affiliations
- `centres`: union of the assigned radiation-oncology cities across all authors
- `authors[]`: `position`, `author_id`, `name`, `cities` (assigned radiation-oncology
  cities, strict), `country`, `region` (Ost/West/Berlin for DE; null for AT/CH),
  `is_senior` (last-author–defined senior set)

The `cities`/`country`/`region`/`is_senior` fields are *derived* labels. The
affiliation-disambiguation method that produces them is described in, and released
with, the companion methods paper.

## Author / creator
David Kaul — Professur für Strahlentherapie, HMU Health and Medical University,
Potsdam, Germany. ORCID: 0000-0002-7906-5629

## How to cite
Kaul D, et al. DACH radiation-oncology corpus — deposit snapshot (2000–2025).
Zenodo; 2026. [DOI]. Underlying records: OpenAlex (https://openalex.org).

## Provenance & licence
Underlying records are from OpenAlex (https://openalex.org, CC0). This derived
snapshot is released under CC0 / CC-BY by the author named above. Generated by
`export_snapshot.py`.
"""


def main() -> None:
    DATASET.mkdir(parents=True, exist_ok=True)
    senior_ids, senior_keys = g.load_senior_set()
    out = DATASET / "corpus_snapshot.jsonl"
    n = 0
    with open(out, "w", encoding="utf-8") as f:
        for w in rc.read_jsonl("refs.jsonl"):
            rec = article_record(w, senior_ids, senior_keys)
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")
            n += 1
    # Manifest mitkopieren (falls vorhanden)
    prov = config.TABLES / "corpus_provenance.json"
    if prov.exists():
        shutil.copy(prov, DATASET / "corpus_provenance.json")
    (DATASET / "README.md").write_text(README, encoding="utf-8")
    size_mb = out.stat().st_size / 1e6
    print(f"[snapshot] {n} Artikel -> {out}  ({size_mb:.1f} MB)")
    print(f"[snapshot] + corpus_provenance.json, README.md in {DATASET}")


if __name__ == "__main__":
    main()
